// Generated by CoffeeScript 1.7.1
(function() {
  var Airbud, fs, request, retry;

  request = require("request");

  fs = require("fs");

  retry = require("retry");

  Airbud = (function() {
    function Airbud() {}

    Airbud._defaults = {
      parseJson: true,
      retries: 0,
      timeout: null,
      testDelay: 0,
      expectedKey: null
    };

    Airbud.fetch = function(options, cb) {
      var key, operation, operationDurations, timeoutForOperation, totalStart, val, _ref;
      _ref = this._defaults;
      for (key in _ref) {
        val = _ref[key];
        if (options[key] == null) {
          options[key] = val;
        }
      }
      if (!options.url) {
        return cb(new Error("You did not specify a url to fetch"));
      }
      operation = retry.operation(options);
      timeoutForOperation = null;
      if (options.timeout != null) {
        timeoutForOperation = {
          timeout: options.timeout,
          cb: function() {
            return operation.retry(new Error("Operation timeout of " + options.timeout + "ms reached. "));
          }
        };
      }
      totalStart = +(new Date);
      operationDurations = 0;
      return operation.attempt((function(_this) {
        return function(currentAttempt) {
          var operationStart;
          operationStart = +(new Date);
          return _this._fetch(options, function(err, data) {
            var info, totalDuration;
            operationDurations += +(new Date) - operationStart;
            if (operation.retry(err)) {
              return;
            }
            totalDuration = +(new Date) - totalStart;
            info = {
              errors: operation.errors(),
              attempts: operation.attempts(),
              totalDuration: totalDuration,
              operationDuration: operationDurations / operation.attempts()
            };
            return cb(operation.mainError(), data, info);
          });
        };
      })(this), timeoutForOperation);
    };

    Airbud._fetch = function(options, cb) {
      var path;
      if (options.url.indexOf("file://") === 0) {
        path = options.url.substr(7, options.url.length).split("?")[0];
        setTimeout((function(_this) {
          return function() {
            return fs.readFile(path, "utf8", function(err, buf) {
              if (err) {
                return cb(new Error("Error while opening " + path + ". " + err.message));
              }
              return _this.handleData(options, buf, cb);
            });
          };
        })(this), options.testDelay);
        return;
      }
      return request.get(options.url, (function(_this) {
        return function(err, res, buf) {
          if (err) {
            return cb(err, buf);
          }
          if (options.expectedStatus != null) {
            if (options.expectedStatus.indexOf(parseInt(res.statusCode, 10)) === -1) {
              return cb(new Error(("" + res.statusCode + " received when fetching '" + url + "'. \n") + ("expected one status of: " + (options.expectedStatus.join(', ')) + ". " + buf + " ")));
            }
          }
          return _this.handleData(options, buf, cb);
        };
      })(this));
    };

    Airbud.handleData = function(options, buf, cb) {
      var data, e;
      data = buf;
      if (options.parseJson) {
        try {
          data = JSON.parse(data);
        } catch (_error) {
          e = _error;
          return cb(e, data);
        }
        if (options.expectedKey != null) {
          if (data[options.expectedKey] == null) {
            return cb(new Error(("Invalid body received when fetching '" + options.url + "'. \n") + ("No key: " + options.expectedKey + ". " + buf)));
          }
        }
      }
      return cb(null, data);
    };

    return Airbud;

  })();

  module.exports = Airbud;

}).call(this);
